// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LEVELPACK_FLAT_H_
#define FLATBUFFERS_GENERATED_LEVELPACK_FLAT_H_

#include "flatbuffers/flatbuffers.h"

namespace flat {

struct LevelRef;
struct LevelRefBuilder;

struct LevelGroup;
struct LevelGroupBuilder;

struct LevelPack;
struct LevelPackBuilder;

struct LevelRef FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LevelRefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEVELNAME = 4,
    VT_LEVELPATH = 6
  };
  const flatbuffers::String *levelName() const {
    return GetPointer<const flatbuffers::String *>(VT_LEVELNAME);
  }
  const flatbuffers::String *levelPath() const {
    return GetPointer<const flatbuffers::String *>(VT_LEVELPATH);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LEVELNAME) &&
           verifier.VerifyString(levelName()) &&
           VerifyOffset(verifier, VT_LEVELPATH) &&
           verifier.VerifyString(levelPath()) &&
           verifier.EndTable();
  }
};

struct LevelRefBuilder {
  typedef LevelRef Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_levelName(flatbuffers::Offset<flatbuffers::String> levelName) {
    fbb_.AddOffset(LevelRef::VT_LEVELNAME, levelName);
  }
  void add_levelPath(flatbuffers::Offset<flatbuffers::String> levelPath) {
    fbb_.AddOffset(LevelRef::VT_LEVELPATH, levelPath);
  }
  explicit LevelRefBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LevelRefBuilder &operator=(const LevelRefBuilder &);
  flatbuffers::Offset<LevelRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LevelRef>(end);
    return o;
  }
};

inline flatbuffers::Offset<LevelRef> CreateLevelRef(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> levelName = 0,
    flatbuffers::Offset<flatbuffers::String> levelPath = 0) {
  LevelRefBuilder builder_(_fbb);
  builder_.add_levelPath(levelPath);
  builder_.add_levelName(levelName);
  return builder_.Finish();
}

inline flatbuffers::Offset<LevelRef> CreateLevelRefDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *levelName = nullptr,
    const char *levelPath = nullptr) {
  auto levelName__ = levelName ? _fbb.CreateString(levelName) : 0;
  auto levelPath__ = levelPath ? _fbb.CreateString(levelPath) : 0;
  return flat::CreateLevelRef(
      _fbb,
      levelName__,
      levelPath__);
}

struct LevelGroup FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LevelGroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUPNAME = 4,
    VT_GOURPHASH = 6,
    VT_MAXLEVELSINAGROUP = 8,
    VT_MAXLEVELSIZEINGROUP = 10,
    VT_LEVELS = 12
  };
  const flatbuffers::String *groupName() const {
    return GetPointer<const flatbuffers::String *>(VT_GROUPNAME);
  }
  uint64_t gourpHash() const {
    return GetField<uint64_t>(VT_GOURPHASH, 0);
  }
  uint32_t maxLevelsInAGroup() const {
    return GetField<uint32_t>(VT_MAXLEVELSINAGROUP, 0);
  }
  uint32_t maxLevelSizeInGroup() const {
    return GetField<uint32_t>(VT_MAXLEVELSIZEINGROUP, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::LevelRef>> *levels() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::LevelRef>> *>(VT_LEVELS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GROUPNAME) &&
           verifier.VerifyString(groupName()) &&
           VerifyField<uint64_t>(verifier, VT_GOURPHASH) &&
           VerifyField<uint32_t>(verifier, VT_MAXLEVELSINAGROUP) &&
           VerifyField<uint32_t>(verifier, VT_MAXLEVELSIZEINGROUP) &&
           VerifyOffset(verifier, VT_LEVELS) &&
           verifier.VerifyVector(levels()) &&
           verifier.VerifyVectorOfTables(levels()) &&
           verifier.EndTable();
  }
};

struct LevelGroupBuilder {
  typedef LevelGroup Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_groupName(flatbuffers::Offset<flatbuffers::String> groupName) {
    fbb_.AddOffset(LevelGroup::VT_GROUPNAME, groupName);
  }
  void add_gourpHash(uint64_t gourpHash) {
    fbb_.AddElement<uint64_t>(LevelGroup::VT_GOURPHASH, gourpHash, 0);
  }
  void add_maxLevelsInAGroup(uint32_t maxLevelsInAGroup) {
    fbb_.AddElement<uint32_t>(LevelGroup::VT_MAXLEVELSINAGROUP, maxLevelsInAGroup, 0);
  }
  void add_maxLevelSizeInGroup(uint32_t maxLevelSizeInGroup) {
    fbb_.AddElement<uint32_t>(LevelGroup::VT_MAXLEVELSIZEINGROUP, maxLevelSizeInGroup, 0);
  }
  void add_levels(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::LevelRef>>> levels) {
    fbb_.AddOffset(LevelGroup::VT_LEVELS, levels);
  }
  explicit LevelGroupBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LevelGroupBuilder &operator=(const LevelGroupBuilder &);
  flatbuffers::Offset<LevelGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LevelGroup>(end);
    return o;
  }
};

inline flatbuffers::Offset<LevelGroup> CreateLevelGroup(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> groupName = 0,
    uint64_t gourpHash = 0,
    uint32_t maxLevelsInAGroup = 0,
    uint32_t maxLevelSizeInGroup = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::LevelRef>>> levels = 0) {
  LevelGroupBuilder builder_(_fbb);
  builder_.add_gourpHash(gourpHash);
  builder_.add_levels(levels);
  builder_.add_maxLevelSizeInGroup(maxLevelSizeInGroup);
  builder_.add_maxLevelsInAGroup(maxLevelsInAGroup);
  builder_.add_groupName(groupName);
  return builder_.Finish();
}

inline flatbuffers::Offset<LevelGroup> CreateLevelGroupDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *groupName = nullptr,
    uint64_t gourpHash = 0,
    uint32_t maxLevelsInAGroup = 0,
    uint32_t maxLevelSizeInGroup = 0,
    const std::vector<flatbuffers::Offset<flat::LevelRef>> *levels = nullptr) {
  auto groupName__ = groupName ? _fbb.CreateString(groupName) : 0;
  auto levels__ = levels ? _fbb.CreateVector<flatbuffers::Offset<flat::LevelRef>>(*levels) : 0;
  return flat::CreateLevelGroup(
      _fbb,
      groupName__,
      gourpHash,
      maxLevelsInAGroup,
      maxLevelSizeInGroup,
      levels__);
}

struct LevelPack FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LevelPackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAXLEVELSIZE = 4,
    VT_ALLLEVELS = 6
  };
  uint32_t maxLevelSize() const {
    return GetField<uint32_t>(VT_MAXLEVELSIZE, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::LevelGroup>> *allLevels() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::LevelGroup>> *>(VT_ALLLEVELS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAXLEVELSIZE) &&
           VerifyOffset(verifier, VT_ALLLEVELS) &&
           verifier.VerifyVector(allLevels()) &&
           verifier.VerifyVectorOfTables(allLevels()) &&
           verifier.EndTable();
  }
};

struct LevelPackBuilder {
  typedef LevelPack Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_maxLevelSize(uint32_t maxLevelSize) {
    fbb_.AddElement<uint32_t>(LevelPack::VT_MAXLEVELSIZE, maxLevelSize, 0);
  }
  void add_allLevels(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::LevelGroup>>> allLevels) {
    fbb_.AddOffset(LevelPack::VT_ALLLEVELS, allLevels);
  }
  explicit LevelPackBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LevelPackBuilder &operator=(const LevelPackBuilder &);
  flatbuffers::Offset<LevelPack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LevelPack>(end);
    return o;
  }
};

inline flatbuffers::Offset<LevelPack> CreateLevelPack(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t maxLevelSize = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::LevelGroup>>> allLevels = 0) {
  LevelPackBuilder builder_(_fbb);
  builder_.add_allLevels(allLevels);
  builder_.add_maxLevelSize(maxLevelSize);
  return builder_.Finish();
}

inline flatbuffers::Offset<LevelPack> CreateLevelPackDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t maxLevelSize = 0,
    const std::vector<flatbuffers::Offset<flat::LevelGroup>> *allLevels = nullptr) {
  auto allLevels__ = allLevels ? _fbb.CreateVector<flatbuffers::Offset<flat::LevelGroup>>(*allLevels) : 0;
  return flat::CreateLevelPack(
      _fbb,
      maxLevelSize,
      allLevels__);
}

inline const flat::LevelPack *GetLevelPack(const void *buf) {
  return flatbuffers::GetRoot<flat::LevelPack>(buf);
}

inline const flat::LevelPack *GetSizePrefixedLevelPack(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::LevelPack>(buf);
}

inline const char *LevelPackIdentifier() {
  return "rlpk";
}

inline bool LevelPackBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, LevelPackIdentifier());
}

inline bool VerifyLevelPackBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::LevelPack>(LevelPackIdentifier());
}

inline bool VerifySizePrefixedLevelPackBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::LevelPack>(LevelPackIdentifier());
}

inline const char *LevelPackExtension() {
  return "rlpk";
}

inline void FinishLevelPackBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::LevelPack> root) {
  fbb.Finish(root, LevelPackIdentifier());
}

inline void FinishSizePrefixedLevelPackBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::LevelPack> root) {
  fbb.FinishSizePrefixed(root, LevelPackIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_LEVELPACK_FLAT_H_
