//
//  SDL2Input.cpp
//  r2engine
//
//  Created by Serge Lansiquot on 2019-02-09.
//

#include "r2pch.h"
#include "SDL2Input.h"
#include <SDL2/SDL.h>

namespace r2
{
    namespace io
    {
        u8 MOUSE_BUTTON_LEFT = SDL_BUTTON_LEFT;
        u8 MOUSE_BUTTON_RIGHT = SDL_BUTTON_RIGHT;
        u8 MOUSE_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE;
        
        u8 BUTTON_PRESSED = SDL_PRESSED;
        u8 BUTTON_RELEASED = SDL_RELEASED;
        
        u32 MOUSE_DIRECTION_NORMAL = SDL_MOUSEWHEEL_NORMAL;
        u32 MOUSE_DIRECTION_FLIPPED = SDL_MOUSEWHEEL_FLIPPED;
        
        u32 SHIFT_PRESSED_BTN = KMOD_SHIFT;
        u32 CTRL_PRESSED = KMOD_CTRL;
        u32 ALT_PRESSED = KMOD_ALT;
        
        s32 KEY_RETURN = SDL_SCANCODE_RETURN;
        s32 KEY_ESCAPE = SDL_SCANCODE_ESCAPE;
        s32 KEY_BACKSPACE = SDL_SCANCODE_BACKSPACE;
        s32 KEY_TAB = SDL_SCANCODE_TAB;
        s32 KEY_SPACE = SDL_SCANCODE_SPACE;
        s32 KEY_EXCLAIM = SDL_SCANCODE_KP_EXCLAM;
        s32 KEY_QUOTEDBL = SDLK_QUOTEDBL;
        s32 KEY_HASH = SDL_SCANCODE_KP_HASH;
        s32 KEY_PERCENT = SDL_SCANCODE_KP_PERCENT;
        s32 KEY_DOLLAR = SDLK_DOLLAR;
        s32 KEY_AMPERSAND = SDL_SCANCODE_KP_AMPERSAND;
        s32 KEY_QUOTE = SDL_SCANCODE_APOSTROPHE;
        s32 KEY_LEFTPAREN = SDL_SCANCODE_KP_LEFTPAREN;
        s32 KEY_RIGHTPAREN = SDL_SCANCODE_KP_RIGHTPAREN;
        s32 KEY_ASTERISK = SDLK_ASTERISK;
        s32 KEY_PLUS = SDL_SCANCODE_KP_PLUS;
        s32 KEY_COMMA = SDL_SCANCODE_COMMA;
        s32 KEY_MINUS = SDL_SCANCODE_MINUS;
        s32 KEY_PERIOD = SDL_SCANCODE_PERIOD;
        s32 KEY_SLASH = SDL_SCANCODE_SLASH;
        s32 KEY_0 = SDL_SCANCODE_0;
        s32 KEY_1 = SDL_SCANCODE_1;
        s32 KEY_2 = SDL_SCANCODE_2;
        s32 KEY_3 = SDL_SCANCODE_3;
        s32 KEY_4 = SDL_SCANCODE_4;
        s32 KEY_5 = SDL_SCANCODE_5;
        s32 KEY_6 = SDL_SCANCODE_6;
        s32 KEY_7 = SDL_SCANCODE_7;
        s32 KEY_8 = SDL_SCANCODE_8;
        s32 KEY_9 = SDL_SCANCODE_9;
        s32 KEY_COLON = SDL_SCANCODE_KP_COLON;
        s32 KEY_SEMICOLON = SDL_SCANCODE_SEMICOLON;
        s32 KEY_LESS = SDL_SCANCODE_KP_LESS;
        s32 KEY_EQUALS = SDL_SCANCODE_EQUALS;
        s32 KEY_GREATER = SDL_SCANCODE_KP_GREATER;
        s32 KEY_QUESTION = SDLK_QUESTION;
        s32 KEY_AT = SDL_SCANCODE_KP_AT;
        
        s32 KEY_LEFTBRACKET = SDL_SCANCODE_LEFTBRACKET;
        s32 KEY_BACKSLASH = SDL_SCANCODE_BACKSLASH;
        s32 KEY_RIGHTBRACKET = SDL_SCANCODE_RIGHTBRACKET;
        s32 KEY_CARET = SDLK_CARET;
        s32 KEY_UNDERSCORE = SDLK_UNDERSCORE;
        s32 KEY_BACKQUOTE = SDL_SCANCODE_GRAVE;
        s32 KEY_a = SDL_SCANCODE_A;
        s32 KEY_b = SDL_SCANCODE_B;
        s32 KEY_c = SDL_SCANCODE_C;
        s32 KEY_d = SDL_SCANCODE_D;
        s32 KEY_e = SDL_SCANCODE_E;
        s32 KEY_f = SDL_SCANCODE_F;
        s32 KEY_g = SDL_SCANCODE_G;
        s32 KEY_h = SDL_SCANCODE_H;
        s32 KEY_i = SDL_SCANCODE_I;
        s32 KEY_j = SDL_SCANCODE_J;
        s32 KEY_k = SDL_SCANCODE_K;
        s32 KEY_l = SDL_SCANCODE_L;
        s32 KEY_m = SDL_SCANCODE_M;
        s32 KEY_n = SDL_SCANCODE_N;
        s32 KEY_o = SDL_SCANCODE_O;
        s32 KEY_p = SDL_SCANCODE_P;
        s32 KEY_q = SDL_SCANCODE_Q;
        s32 KEY_r = SDL_SCANCODE_R;
        s32 KEY_s = SDL_SCANCODE_S;
        s32 KEY_t = SDL_SCANCODE_T;
        s32 KEY_u = SDL_SCANCODE_U;
        s32 KEY_v = SDL_SCANCODE_V;
        s32 KEY_w = SDL_SCANCODE_W;
        s32 KEY_x = SDL_SCANCODE_X;
        s32 KEY_y = SDL_SCANCODE_Y;
        s32 KEY_z = SDL_SCANCODE_Z;
        s32 KEY_CAPSLOCK = SDL_SCANCODE_CAPSLOCK;
        s32 KEY_F1 = SDL_SCANCODE_F1;
        s32 KEY_F2 = SDL_SCANCODE_F2;
        s32 KEY_F3 = SDL_SCANCODE_F3;
        s32 KEY_F4 = SDL_SCANCODE_F4;
        s32 KEY_F5 = SDL_SCANCODE_F5;
        s32 KEY_F6 = SDL_SCANCODE_F6;
        s32 KEY_F7 = SDL_SCANCODE_F7;
        s32 KEY_F8 = SDL_SCANCODE_F8;
        s32 KEY_F9 = SDL_SCANCODE_F9;
        s32 KEY_F10 = SDL_SCANCODE_F10;
        s32 KEY_F11 = SDL_SCANCODE_F11;
        s32 KEY_F12 = SDL_SCANCODE_F12;
        s32 KEY_PRINTSCREEN = SDL_SCANCODE_PRINTSCREEN;
        s32 KEY_SCROLLLOCK = SDL_SCANCODE_SCROLLLOCK;
        s32 KEY_PAUSE = SDL_SCANCODE_PAUSE;
        s32 KEY_INSERT = SDL_SCANCODE_INSERT;
        s32 KEY_HOME = SDL_SCANCODE_HOME;
        s32 KEY_PAGEUP = SDL_SCANCODE_PAGEUP;
        s32 KEY_DELETE = SDL_SCANCODE_DELETE;
        s32 KEY_END = SDL_SCANCODE_END;
        s32 KEY_PAGEDOWN = SDL_SCANCODE_PAGEDOWN;
        s32 KEY_RIGHT = SDL_SCANCODE_RIGHT;
        s32 KEY_LEFT = SDL_SCANCODE_LEFT;
        s32 KEY_DOWN = SDL_SCANCODE_DOWN;
        s32 KEY_UP = SDL_SCANCODE_UP; 
    }
}
