// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEXTUREPACKMETADATA_FLAT_H_
#define FLATBUFFERS_GENERATED_TEXTUREPACKMETADATA_FLAT_H_

#include "flatbuffers/flatbuffers.h"

namespace flat {

struct CubemapSideEntry;
struct CubemapSideEntryBuilder;

struct MipLevel;
struct MipLevelBuilder;

struct TexturePackMetaData;
struct TexturePackMetaDataBuilder;

enum TextureType {
  TextureType_TEXTURE = 0,
  TextureType_CUBEMAP = 1,
  TextureType_MIN = TextureType_TEXTURE,
  TextureType_MAX = TextureType_CUBEMAP
};

inline const TextureType (&EnumValuesTextureType())[2] {
  static const TextureType values[] = {
    TextureType_TEXTURE,
    TextureType_CUBEMAP
  };
  return values;
}

inline const char * const *EnumNamesTextureType() {
  static const char * const names[3] = {
    "TEXTURE",
    "CUBEMAP",
    nullptr
  };
  return names;
}

inline const char *EnumNameTextureType(TextureType e) {
  if (flatbuffers::IsOutRange(e, TextureType_TEXTURE, TextureType_CUBEMAP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTextureType()[index];
}

enum CubemapSide {
  CubemapSide_RIGHT = 0,
  CubemapSide_LEFT = 1,
  CubemapSide_TOP = 2,
  CubemapSide_BOTTOM = 3,
  CubemapSide_FRONT = 4,
  CubemapSide_BACK = 5,
  CubemapSide_NUM_SIDES = 6,
  CubemapSide_MIN = CubemapSide_RIGHT,
  CubemapSide_MAX = CubemapSide_NUM_SIDES
};

inline const CubemapSide (&EnumValuesCubemapSide())[7] {
  static const CubemapSide values[] = {
    CubemapSide_RIGHT,
    CubemapSide_LEFT,
    CubemapSide_TOP,
    CubemapSide_BOTTOM,
    CubemapSide_FRONT,
    CubemapSide_BACK,
    CubemapSide_NUM_SIDES
  };
  return values;
}

inline const char * const *EnumNamesCubemapSide() {
  static const char * const names[8] = {
    "RIGHT",
    "LEFT",
    "TOP",
    "BOTTOM",
    "FRONT",
    "BACK",
    "NUM_SIDES",
    nullptr
  };
  return names;
}

inline const char *EnumNameCubemapSide(CubemapSide e) {
  if (flatbuffers::IsOutRange(e, CubemapSide_RIGHT, CubemapSide_NUM_SIDES)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCubemapSide()[index];
}

struct CubemapSideEntry FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CubemapSideEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEXTURENAME = 4,
    VT_SIDE = 6
  };
  const flatbuffers::String *textureName() const {
    return GetPointer<const flatbuffers::String *>(VT_TEXTURENAME);
  }
  flat::CubemapSide side() const {
    return static_cast<flat::CubemapSide>(GetField<int8_t>(VT_SIDE, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TEXTURENAME) &&
           verifier.VerifyString(textureName()) &&
           VerifyField<int8_t>(verifier, VT_SIDE) &&
           verifier.EndTable();
  }
};

struct CubemapSideEntryBuilder {
  typedef CubemapSideEntry Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_textureName(flatbuffers::Offset<flatbuffers::String> textureName) {
    fbb_.AddOffset(CubemapSideEntry::VT_TEXTURENAME, textureName);
  }
  void add_side(flat::CubemapSide side) {
    fbb_.AddElement<int8_t>(CubemapSideEntry::VT_SIDE, static_cast<int8_t>(side), 0);
  }
  explicit CubemapSideEntryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  CubemapSideEntryBuilder &operator=(const CubemapSideEntryBuilder &);
  flatbuffers::Offset<CubemapSideEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CubemapSideEntry>(end);
    return o;
  }
};

inline flatbuffers::Offset<CubemapSideEntry> CreateCubemapSideEntry(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> textureName = 0,
    flat::CubemapSide side = flat::CubemapSide_RIGHT) {
  CubemapSideEntryBuilder builder_(_fbb);
  builder_.add_textureName(textureName);
  builder_.add_side(side);
  return builder_.Finish();
}

inline flatbuffers::Offset<CubemapSideEntry> CreateCubemapSideEntryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *textureName = nullptr,
    flat::CubemapSide side = flat::CubemapSide_RIGHT) {
  auto textureName__ = textureName ? _fbb.CreateString(textureName) : 0;
  return flat::CreateCubemapSideEntry(
      _fbb,
      textureName__,
      side);
}

struct MipLevel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MipLevelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEVEL = 4,
    VT_SIDES = 6
  };
  uint32_t level() const {
    return GetField<uint32_t>(VT_LEVEL, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::CubemapSideEntry>> *sides() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::CubemapSideEntry>> *>(VT_SIDES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_LEVEL) &&
           VerifyOffset(verifier, VT_SIDES) &&
           verifier.VerifyVector(sides()) &&
           verifier.VerifyVectorOfTables(sides()) &&
           verifier.EndTable();
  }
};

struct MipLevelBuilder {
  typedef MipLevel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_level(uint32_t level) {
    fbb_.AddElement<uint32_t>(MipLevel::VT_LEVEL, level, 0);
  }
  void add_sides(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::CubemapSideEntry>>> sides) {
    fbb_.AddOffset(MipLevel::VT_SIDES, sides);
  }
  explicit MipLevelBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MipLevelBuilder &operator=(const MipLevelBuilder &);
  flatbuffers::Offset<MipLevel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MipLevel>(end);
    return o;
  }
};

inline flatbuffers::Offset<MipLevel> CreateMipLevel(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t level = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::CubemapSideEntry>>> sides = 0) {
  MipLevelBuilder builder_(_fbb);
  builder_.add_sides(sides);
  builder_.add_level(level);
  return builder_.Finish();
}

inline flatbuffers::Offset<MipLevel> CreateMipLevelDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t level = 0,
    const std::vector<flatbuffers::Offset<flat::CubemapSideEntry>> *sides = nullptr) {
  auto sides__ = sides ? _fbb.CreateVector<flatbuffers::Offset<flat::CubemapSideEntry>>(*sides) : 0;
  return flat::CreateMipLevel(
      _fbb,
      level,
      sides__);
}

struct TexturePackMetaData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TexturePackMetaDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_MIPLEVELS = 6
  };
  flat::TextureType type() const {
    return static_cast<flat::TextureType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::MipLevel>> *mipLevels() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::MipLevel>> *>(VT_MIPLEVELS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyOffset(verifier, VT_MIPLEVELS) &&
           verifier.VerifyVector(mipLevels()) &&
           verifier.VerifyVectorOfTables(mipLevels()) &&
           verifier.EndTable();
  }
};

struct TexturePackMetaDataBuilder {
  typedef TexturePackMetaData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_type(flat::TextureType type) {
    fbb_.AddElement<int8_t>(TexturePackMetaData::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_mipLevels(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::MipLevel>>> mipLevels) {
    fbb_.AddOffset(TexturePackMetaData::VT_MIPLEVELS, mipLevels);
  }
  explicit TexturePackMetaDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TexturePackMetaDataBuilder &operator=(const TexturePackMetaDataBuilder &);
  flatbuffers::Offset<TexturePackMetaData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TexturePackMetaData>(end);
    return o;
  }
};

inline flatbuffers::Offset<TexturePackMetaData> CreateTexturePackMetaData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flat::TextureType type = flat::TextureType_TEXTURE,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::MipLevel>>> mipLevels = 0) {
  TexturePackMetaDataBuilder builder_(_fbb);
  builder_.add_mipLevels(mipLevels);
  builder_.add_type(type);
  return builder_.Finish();
}

inline flatbuffers::Offset<TexturePackMetaData> CreateTexturePackMetaDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flat::TextureType type = flat::TextureType_TEXTURE,
    const std::vector<flatbuffers::Offset<flat::MipLevel>> *mipLevels = nullptr) {
  auto mipLevels__ = mipLevels ? _fbb.CreateVector<flatbuffers::Offset<flat::MipLevel>>(*mipLevels) : 0;
  return flat::CreateTexturePackMetaData(
      _fbb,
      type,
      mipLevels__);
}

inline const flat::TexturePackMetaData *GetTexturePackMetaData(const void *buf) {
  return flatbuffers::GetRoot<flat::TexturePackMetaData>(buf);
}

inline const flat::TexturePackMetaData *GetSizePrefixedTexturePackMetaData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::TexturePackMetaData>(buf);
}

inline const char *TexturePackMetaDataIdentifier() {
  return "tmet";
}

inline bool TexturePackMetaDataBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, TexturePackMetaDataIdentifier());
}

inline bool VerifyTexturePackMetaDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::TexturePackMetaData>(TexturePackMetaDataIdentifier());
}

inline bool VerifySizePrefixedTexturePackMetaDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::TexturePackMetaData>(TexturePackMetaDataIdentifier());
}

inline const char *TexturePackMetaDataExtension() {
  return "tmet";
}

inline void FinishTexturePackMetaDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::TexturePackMetaData> root) {
  fbb.Finish(root, TexturePackMetaDataIdentifier());
}

inline void FinishSizePrefixedTexturePackMetaDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::TexturePackMetaData> root) {
  fbb.FinishSizePrefixed(root, TexturePackMetaDataIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_TEXTUREPACKMETADATA_FLAT_H_
