// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SOUNDDEFINITION_FLAT_H_
#define FLATBUFFERS_GENERATED_SOUNDDEFINITION_FLAT_H_

#include "flatbuffers/flatbuffers.h"

namespace flat {

struct BankFile;
struct BankFileBuilder;

struct SoundDefinitions;
struct SoundDefinitionsBuilder;

struct BankFile FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BankFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4
  };
  const flatbuffers::String *path() const {
    return GetPointer<const flatbuffers::String *>(VT_PATH);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct BankFileBuilder {
  typedef BankFile Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_path(flatbuffers::Offset<flatbuffers::String> path) {
    fbb_.AddOffset(BankFile::VT_PATH, path);
  }
  explicit BankFileBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  BankFileBuilder &operator=(const BankFileBuilder &);
  flatbuffers::Offset<BankFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<BankFile>(end);
    return o;
  }
};

inline flatbuffers::Offset<BankFile> CreateBankFile(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> path = 0) {
  BankFileBuilder builder_(_fbb);
  builder_.add_path(path);
  return builder_.Finish();
}

inline flatbuffers::Offset<BankFile> CreateBankFileDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return flat::CreateBankFile(
      _fbb,
      path__);
}

struct SoundDefinitions FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SoundDefinitionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MASTERBANK = 4,
    VT_MASTERBANKSTRINGS = 6,
    VT_BANKS = 8
  };
  const flat::BankFile *masterBank() const {
    return GetPointer<const flat::BankFile *>(VT_MASTERBANK);
  }
  const flat::BankFile *masterBankStrings() const {
    return GetPointer<const flat::BankFile *>(VT_MASTERBANKSTRINGS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::BankFile>> *banks() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::BankFile>> *>(VT_BANKS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MASTERBANK) &&
           verifier.VerifyTable(masterBank()) &&
           VerifyOffset(verifier, VT_MASTERBANKSTRINGS) &&
           verifier.VerifyTable(masterBankStrings()) &&
           VerifyOffset(verifier, VT_BANKS) &&
           verifier.VerifyVector(banks()) &&
           verifier.VerifyVectorOfTables(banks()) &&
           verifier.EndTable();
  }
};

struct SoundDefinitionsBuilder {
  typedef SoundDefinitions Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_masterBank(flatbuffers::Offset<flat::BankFile> masterBank) {
    fbb_.AddOffset(SoundDefinitions::VT_MASTERBANK, masterBank);
  }
  void add_masterBankStrings(flatbuffers::Offset<flat::BankFile> masterBankStrings) {
    fbb_.AddOffset(SoundDefinitions::VT_MASTERBANKSTRINGS, masterBankStrings);
  }
  void add_banks(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::BankFile>>> banks) {
    fbb_.AddOffset(SoundDefinitions::VT_BANKS, banks);
  }
  explicit SoundDefinitionsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SoundDefinitionsBuilder &operator=(const SoundDefinitionsBuilder &);
  flatbuffers::Offset<SoundDefinitions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SoundDefinitions>(end);
    return o;
  }
};

inline flatbuffers::Offset<SoundDefinitions> CreateSoundDefinitions(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flat::BankFile> masterBank = 0,
    flatbuffers::Offset<flat::BankFile> masterBankStrings = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::BankFile>>> banks = 0) {
  SoundDefinitionsBuilder builder_(_fbb);
  builder_.add_banks(banks);
  builder_.add_masterBankStrings(masterBankStrings);
  builder_.add_masterBank(masterBank);
  return builder_.Finish();
}

inline flatbuffers::Offset<SoundDefinitions> CreateSoundDefinitionsDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flat::BankFile> masterBank = 0,
    flatbuffers::Offset<flat::BankFile> masterBankStrings = 0,
    const std::vector<flatbuffers::Offset<flat::BankFile>> *banks = nullptr) {
  auto banks__ = banks ? _fbb.CreateVector<flatbuffers::Offset<flat::BankFile>>(*banks) : 0;
  return flat::CreateSoundDefinitions(
      _fbb,
      masterBank,
      masterBankStrings,
      banks__);
}

inline const flat::SoundDefinitions *GetSoundDefinitions(const void *buf) {
  return flatbuffers::GetRoot<flat::SoundDefinitions>(buf);
}

inline const flat::SoundDefinitions *GetSizePrefixedSoundDefinitions(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::SoundDefinitions>(buf);
}

inline const char *SoundDefinitionsIdentifier() {
  return "sdef";
}

inline bool SoundDefinitionsBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, SoundDefinitionsIdentifier());
}

inline bool VerifySoundDefinitionsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::SoundDefinitions>(SoundDefinitionsIdentifier());
}

inline bool VerifySizePrefixedSoundDefinitionsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::SoundDefinitions>(SoundDefinitionsIdentifier());
}

inline const char *SoundDefinitionsExtension() {
  return "sdef";
}

inline void FinishSoundDefinitionsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::SoundDefinitions> root) {
  fbb.Finish(root, SoundDefinitionsIdentifier());
}

inline void FinishSizePrefixedSoundDefinitionsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::SoundDefinitions> root) {
  fbb.FinishSizePrefixed(root, SoundDefinitionsIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_SOUNDDEFINITION_FLAT_H_
