// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SHADERMANIFEST_R2_H_
#define FLATBUFFERS_GENERATED_SHADERMANIFEST_R2_H_

#include "flatbuffers/flatbuffers.h"

namespace r2 {

struct ShaderManifest;

struct ShaderManifests;

struct ShaderManifest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_VERTEXPATH = 4,
    VT_FRAGMENTPATH = 6,
    VT_BINARYPATH = 8
  };
  const flatbuffers::String *vertexPath() const {
    return GetPointer<const flatbuffers::String *>(VT_VERTEXPATH);
  }
  const flatbuffers::String *fragmentPath() const {
    return GetPointer<const flatbuffers::String *>(VT_FRAGMENTPATH);
  }
  const flatbuffers::String *binaryPath() const {
    return GetPointer<const flatbuffers::String *>(VT_BINARYPATH);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTEXPATH) &&
           verifier.VerifyString(vertexPath()) &&
           VerifyOffset(verifier, VT_FRAGMENTPATH) &&
           verifier.VerifyString(fragmentPath()) &&
           VerifyOffset(verifier, VT_BINARYPATH) &&
           verifier.VerifyString(binaryPath()) &&
           verifier.EndTable();
  }
};

struct ShaderManifestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_vertexPath(flatbuffers::Offset<flatbuffers::String> vertexPath) {
    fbb_.AddOffset(ShaderManifest::VT_VERTEXPATH, vertexPath);
  }
  void add_fragmentPath(flatbuffers::Offset<flatbuffers::String> fragmentPath) {
    fbb_.AddOffset(ShaderManifest::VT_FRAGMENTPATH, fragmentPath);
  }
  void add_binaryPath(flatbuffers::Offset<flatbuffers::String> binaryPath) {
    fbb_.AddOffset(ShaderManifest::VT_BINARYPATH, binaryPath);
  }
  explicit ShaderManifestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ShaderManifestBuilder &operator=(const ShaderManifestBuilder &);
  flatbuffers::Offset<ShaderManifest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ShaderManifest>(end);
    return o;
  }
};

inline flatbuffers::Offset<ShaderManifest> CreateShaderManifest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> vertexPath = 0,
    flatbuffers::Offset<flatbuffers::String> fragmentPath = 0,
    flatbuffers::Offset<flatbuffers::String> binaryPath = 0) {
  ShaderManifestBuilder builder_(_fbb);
  builder_.add_binaryPath(binaryPath);
  builder_.add_fragmentPath(fragmentPath);
  builder_.add_vertexPath(vertexPath);
  return builder_.Finish();
}

inline flatbuffers::Offset<ShaderManifest> CreateShaderManifestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *vertexPath = nullptr,
    const char *fragmentPath = nullptr,
    const char *binaryPath = nullptr) {
  return r2::CreateShaderManifest(
      _fbb,
      vertexPath ? _fbb.CreateString(vertexPath) : 0,
      fragmentPath ? _fbb.CreateString(fragmentPath) : 0,
      binaryPath ? _fbb.CreateString(binaryPath) : 0);
}

struct ShaderManifests FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_MANIFESTS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<ShaderManifest>> *manifests() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ShaderManifest>> *>(VT_MANIFESTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MANIFESTS) &&
           verifier.VerifyVector(manifests()) &&
           verifier.VerifyVectorOfTables(manifests()) &&
           verifier.EndTable();
  }
};

struct ShaderManifestsBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_manifests(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ShaderManifest>>> manifests) {
    fbb_.AddOffset(ShaderManifests::VT_MANIFESTS, manifests);
  }
  explicit ShaderManifestsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ShaderManifestsBuilder &operator=(const ShaderManifestsBuilder &);
  flatbuffers::Offset<ShaderManifests> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ShaderManifests>(end);
    return o;
  }
};

inline flatbuffers::Offset<ShaderManifests> CreateShaderManifests(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ShaderManifest>>> manifests = 0) {
  ShaderManifestsBuilder builder_(_fbb);
  builder_.add_manifests(manifests);
  return builder_.Finish();
}

inline flatbuffers::Offset<ShaderManifests> CreateShaderManifestsDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<ShaderManifest>> *manifests = nullptr) {
  return r2::CreateShaderManifests(
      _fbb,
      manifests ? _fbb.CreateVector<flatbuffers::Offset<ShaderManifest>>(*manifests) : 0);
}

inline const r2::ShaderManifests *GetShaderManifests(const void *buf) {
  return flatbuffers::GetRoot<r2::ShaderManifests>(buf);
}

inline const r2::ShaderManifests *GetSizePrefixedShaderManifests(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<r2::ShaderManifests>(buf);
}

inline const char *ShaderManifestsIdentifier() {
  return "sman";
}

inline bool ShaderManifestsBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, ShaderManifestsIdentifier());
}

inline bool VerifyShaderManifestsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<r2::ShaderManifests>(ShaderManifestsIdentifier());
}

inline bool VerifySizePrefixedShaderManifestsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<r2::ShaderManifests>(ShaderManifestsIdentifier());
}

inline const char *ShaderManifestsExtension() {
  return "sman";
}

inline void FinishShaderManifestsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<r2::ShaderManifests> root) {
  fbb.Finish(root, ShaderManifestsIdentifier());
}

inline void FinishSizePrefixedShaderManifestsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<r2::ShaderManifests> root) {
  fbb.FinishSizePrefixed(root, ShaderManifestsIdentifier());
}

}  // namespace r2

#endif  // FLATBUFFERS_GENERATED_SHADERMANIFEST_R2_H_
