// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RMODELMANIFEST_FLAT_H_
#define FLATBUFFERS_GENERATED_RMODELMANIFEST_FLAT_H_

#include "flatbuffers/flatbuffers.h"

#include "AssetName_generated.h"
#include "AssetRef_generated.h"

namespace flat {

struct RModelsManifest;
struct RModelsManifestBuilder;

struct RModelsManifest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RModelsManifestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ASSETNAME = 6,
    VT_MODELS = 8
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const flat::AssetName *assetName() const {
    return GetPointer<const flat::AssetName *>(VT_ASSETNAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::AssetRef>> *models() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::AssetRef>> *>(VT_MODELS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION) &&
           VerifyOffset(verifier, VT_ASSETNAME) &&
           verifier.VerifyTable(assetName()) &&
           VerifyOffset(verifier, VT_MODELS) &&
           verifier.VerifyVector(models()) &&
           verifier.VerifyVectorOfTables(models()) &&
           verifier.EndTable();
  }
};

struct RModelsManifestBuilder {
  typedef RModelsManifest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(RModelsManifest::VT_VERSION, version, 0);
  }
  void add_assetName(flatbuffers::Offset<flat::AssetName> assetName) {
    fbb_.AddOffset(RModelsManifest::VT_ASSETNAME, assetName);
  }
  void add_models(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::AssetRef>>> models) {
    fbb_.AddOffset(RModelsManifest::VT_MODELS, models);
  }
  explicit RModelsManifestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  RModelsManifestBuilder &operator=(const RModelsManifestBuilder &);
  flatbuffers::Offset<RModelsManifest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RModelsManifest>(end);
    return o;
  }
};

inline flatbuffers::Offset<RModelsManifest> CreateRModelsManifest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    flatbuffers::Offset<flat::AssetName> assetName = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::AssetRef>>> models = 0) {
  RModelsManifestBuilder builder_(_fbb);
  builder_.add_models(models);
  builder_.add_assetName(assetName);
  builder_.add_version(version);
  return builder_.Finish();
}

inline flatbuffers::Offset<RModelsManifest> CreateRModelsManifestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    flatbuffers::Offset<flat::AssetName> assetName = 0,
    const std::vector<flatbuffers::Offset<flat::AssetRef>> *models = nullptr) {
  auto models__ = models ? _fbb.CreateVector<flatbuffers::Offset<flat::AssetRef>>(*models) : 0;
  return flat::CreateRModelsManifest(
      _fbb,
      version,
      assetName,
      models__);
}

inline const flat::RModelsManifest *GetRModelsManifest(const void *buf) {
  return flatbuffers::GetRoot<flat::RModelsManifest>(buf);
}

inline const flat::RModelsManifest *GetSizePrefixedRModelsManifest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::RModelsManifest>(buf);
}

inline const char *RModelsManifestIdentifier() {
  return "rmmn";
}

inline bool RModelsManifestBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, RModelsManifestIdentifier());
}

inline bool VerifyRModelsManifestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::RModelsManifest>(RModelsManifestIdentifier());
}

inline bool VerifySizePrefixedRModelsManifestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::RModelsManifest>(RModelsManifestIdentifier());
}

inline const char *RModelsManifestExtension() {
  return "rmmn";
}

inline void FinishRModelsManifestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::RModelsManifest> root) {
  fbb.Finish(root, RModelsManifestIdentifier());
}

inline void FinishSizePrefixedRModelsManifestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::RModelsManifest> root) {
  fbb.FinishSizePrefixed(root, RModelsManifestIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_RMODELMANIFEST_FLAT_H_
